"""Baseline schema D1-D6 (Phase 2).

Revision ID: 0001
Revises: (none)
Create Date: 2026-10-03

Autogenerated from the SQLAlchemy models against PostgreSQL 16, then reviewed
by hand. Differences from the tables the app used to create with create_all():

- users.registered_at, users.otp_expires_at, images.upload_timestamp are
  timezone-aware (they were naive; every other timestamp already was).
- Email uniqueness is case-insensitive: unique index on lower(email),
  replacing the plain unique constraint on the raw column.
- models: partial unique index - at most one active row per model_type.
- predictions.cold_start (nullable boolean) - was a branch loaded inside the
  request; excluded from latency statistics.
- images: the duplicate single-column index on content_sha256 is gone
  (idx_images_sha already covered it).

test_migrations.py asserts that this history produces exactly the models'
schema on SQLite and PostgreSQL.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('artifact_ref', sa.Text(), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('model_name', 'model_version', name='uq_model_name_version')
    )
    op.create_index('uq_models_one_active_per_type', 'models', ['model_type'], unique=True, postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active = 1'))
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('account_status', sa.String(length=10), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.CheckConstraint("account_status IN ('active', 'disabled', 'removed')", name='chk_user_status'),
    sa.CheckConstraint("role IN ('User', 'Admin')", name='chk_user_role'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_reference', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_format', sa.String(length=5), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_status', sa.String(length=10), nullable=False),
    sa.Column('rejection_reason', sa.String(length=32), nullable=True),
    sa.CheckConstraint("file_format IN ('JPG', 'JPEG', 'PNG')", name='chk_image_format'),
    sa.CheckConstraint("rejection_reason IS NULL OR rejection_reason IN ('unsupported-format', 'file-too-large', 'corrupted-file')", name='chk_rejection_reason'),
    sa.CheckConstraint("validation_status IN ('pending', 'valid', 'invalid')", name='chk_validation_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index('idx_images_sha', 'images', ['content_sha256'], unique=False)
    op.create_index('idx_images_user_time', 'images', ['user_id', 'upload_timestamp'], unique=False)
    op.create_index(op.f('ix_images_image_id'), 'images', ['image_id'], unique=False)
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('event_detail', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_logs_sev_time', 'logs', ['severity', sa.literal_column('log_timestamp DESC')], unique=False)
    op.create_index('idx_logs_time', 'logs', [sa.literal_column('log_timestamp DESC')], unique=False)
    op.create_index('idx_logs_type_time', 'logs', ['event_type', sa.literal_column('log_timestamp DESC')], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('branch_model_ids', sa.JSON(), nullable=True),
    sa.Column('predicted_class', sa.String(length=14), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=True),
    sa.Column('fusion_score', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cold_start', sa.Boolean(), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.image_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('idx_pred_time', 'predictions', [sa.literal_column('prediction_timestamp DESC')], unique=False)
    op.create_index(op.f('ix_predictions_image_id'), 'predictions', ['image_id'], unique=False)
    op.create_table('explainability',
    sa.Column('explainability_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=12), nullable=False),
    sa.Column('technique', sa.String(length=40), nullable=False),
    sa.Column('visualization_reference', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explainability_id'),
    sa.UniqueConstraint('prediction_id', 'branch', name='uq_prediction_branch')
    )
    op.create_index(op.f('ix_explainability_prediction_id'), 'explainability', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explainability_prediction_id'), table_name='explainability')
    op.drop_table('explainability')
    op.drop_index(op.f('ix_predictions_image_id'), table_name='predictions')
    op.drop_index('idx_pred_time', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_logs_type_time', table_name='logs')
    op.drop_index('idx_logs_time', table_name='logs')
    op.drop_index('idx_logs_sev_time', table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_images_image_id'), table_name='images')
    op.drop_index('idx_images_user_time', table_name='images')
    op.drop_index('idx_images_sha', table_name='images')
    op.drop_table('images')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_models_one_active_per_type', table_name='models', postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active = 1'))
    op.drop_table('models')
    # ### end Alembic commands ###
